@echo off
echo Démarrage du service chatbot...
echo Vérification des dossiers nécessaires...

if not exist "models" (
    echo Création du dossier models...
    mkdir models
)

echo Lancement du service chatbot...
cd %~dp0
python "scripts\chatbot_service.py" --host=0.0.0.0 --port=5001
