@echo off
echo Démarrage de tous les services...

echo Démarrage du service chatbot...
start cmd /k "cd %~dp0 && node start-chatbot.js"

echo Démarrage de l'environnement de développement...
npm run dev
